name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  TAG: 335902315655.dkr.ecr.us-east-1.amazonaws.com/github-actions

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker image
        run: docker build . -t "$TAG"

      - name: Publish the Docker image to AWS ECR
        run: docker push "$TAG"
      
