name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  TAG: "$ECR_REGISTRY:$(date +%s)"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::335902315655:role/github-actions-ecr
          aws-access-key-id: AKIAU4NKWSSD3ICMTPOG
          aws-region: us-east-1
          aws-secret-access-key: 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
          role-skip-session-tagging: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $TAG

      - name: Publish the Docker image to AWS ECR
        run: docker push $TAG
      
