name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  TAG: 335902315655.dkr.ecr.us-east-1.amazonaws.com/github-actions

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt update 
      #     sudo apt install awscli

      - name: Teste de autenticação AWS
        run: |
          # aws --version
          echo "${{ vars.AWS_ACCESS_KEY_ID }}"
          echo "${{ vars.AWS_SECRET_ACCESS_KEY }}"



# name: 1 - Build and Publish Docker to ECR

# on:
#   release:
#     types:
#       - created

# jobs:
#   build:
#     name: Build Image Docker
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2

#     - name: Build, tag, and push docker image to Amazon ECR
#       env:
#         REGISTRY: 949104489699.dkr.ecr.us-east-1.amazonaws.com
#         REPOSITORY: oncargas-backend
#         IMAGE_TAG: ${{ github.event.release.tag_name }}
#       run: |
#         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      # - name: Login to Amazon ECR
      # id: login-ecr
      # uses: aws-actions/amazon-ecr-login@v2

      # - name: Build the Docker image
      #   run: docker build . -t "$TAG"

      # - name: Authentication ECR 
      #   run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 335902315655.dkr.ecr.us-east-1.amazonaws.com

      # - name: Publish the Docker image to AWS ECR
      #   run: docker push "$TAG"
      
