name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  TAG: "$ECR_REGISTRY:$(date +%s)"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build the Docker image
        run: docker build -t "$TAG" .

      - name: Publish the Docker image to AWS ECR
        run: docker push "$TAG"
      
