name: Docker Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  TAG: 335902315655.dkr.ecr.us-east-1.amazonaws.com/github-actions

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build the Docker image
        run: docker build . -f ./Dockerfile -t "$TAG"

      - name: Publish the Docker image to AWS ECR
        run: docker push "$TAG"
      
