name: 2 - Deploy ECS

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Docker Image CI/CD]
    types:
      - completed
      
jobs:
  deploy-prod:
    name: Deploy Produção
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition task-lab-github --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
      with:
        task-definition: task-definition.json
        container-name: api-googledrive
        image: 949104489699.dkr.ecr.us-east-1.amazonaws.com/api-googledrive:${{ github.event.inputs.tagVersion }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: service-api-googledrive
        cluster: cluster-api-google-drive
        wait-for-service-stability: true
